### ISSUE TITLE
Unexpected exception: "Cannot finalized an empty tree"

### ISSUE THREAD

**Issue by jtraglia** [Consensys/teku#5646] opened 2022-05-31 16:14 UTC
### Description

Sorry, I don't have many details and I don't have a log file. I was setting up ropsten nodes and encountered this issue:

```
ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.storage.api.FinalizedCheckpointChannel.onNewFinalizedCheckpoint' in handler 'tech.pegasys.teku.validator.coordinator.DepositProvider' java.lang.UnsupportedOperationException: Cannot finalized an empty tree (See log file for full stack trace)
```

It would repeatedly happen, see this except for more details:

https://gist.github.com/jtraglia/f0e745bfe66112bcd47dbc8446c03ae0

### Steps to Reproduce (Bug)

Not sure if reproducible.

### Versions (Add all that apply)
* Software version: Teku master as of 6 days ago

**Comment by benjaminion** [comment] 2022-05-31 16:41
Thanks for reporting! This is a duplicate of #5617, and fixed by #5619. Seems like it just missed making it into the 22.5.2 release, unfortunately, but should be fixed in current `master`.

**Closed as completed by benjaminion** 2022-05-31 16:41 UTC

**Comment by jtraglia** [comment] 2022-05-31 16:58
Ah perfect. Thanks!

**Comment by ajsutton** [comment] 2022-06-01 00:26
For the record, it shouldn't be a problem in the release either. It's an issue with the new deposit merkle tree which we took back out for this release as we'd seen a performance regression (fixed in the commit after the release) and wanted to give it more time for testing before going out for real.
